---
- name: Deploy app in new namespace
  hosts: localhost
  tasks: 
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: namespace
        state: present
        kubeconfig: ~/Desktop/DevOps/terraform/kubeconfig_myapp-eks-cluster
    - name: deploy nginx application
      kubernetes.core.k8s:
        src: ~/Desktop/DevOps/nginx-config.yaml
        state: present
        kubeconfig: ~/Desktop/DevOps/terraform/kubeconfig_myapp-eks-cluster
        namespace: my-app
