---
- name: nginx-ws
  hosts: ws
  tasks: 
  - name: install nginx server
    apt:
      name: nginx
      state: latest
  - name: start nginx server
    service:
      name: nginx
      state: started